### ISSUE TITLE
Garmin Connect failure as of 2/12/2015

### ISSUE THREAD

**Issue by gcyclist** [kochka/WeightLogger#21]
Garmin Connect no  longer  connects as of 2/12/2015.  Issues a message that the username or password are incorrect but the name and password work to log into GC.   There is, however, an agreement message that comes up now so maybe that is causing the failure.

**Comment by maciekz** [comment]
I'm affraid I have to confirm the problem. It looks like the fix from issue #15 is no longer working...

**Comment by kochka** [comment]
Thanks for the report, I will check this.

**Comment by kochka** [comment]
Fixed in 8f6f61cbd80f4bd596cd446cf1f37bee24987f42

**Comment by gcyclist** [comment]
Thanks for such a fast response.  Hate to show my ignorance but how do you install the fix?

**Comment by kochka** [comment]
I've uploaded a new release on Google Play, it should appear shortly for you (It can take several hours).

**Comment by gcyclist** [comment]
Thanks for your support of this app!!  The new version works fine.
