### ISSUE TITLE
Bad username or password

### ISSUE THREAD

**Issue by TrippyZ** [kochka/WeightLogger#26]
After several months of using the app I now get bad username or password.  I have not ever changed my password.  Could you debug the problem?  Thanks, great app!

**Comment by TrippyZ** [comment]
Well, after it not working for ten days, suddenly it is!  I notice that Garmin Connect had outage yesterday so maybe they have fixed something at their end.

**Comment by kochka** [comment]
Very strange, and I didn't had time to investigate so I don't know what happened...
Thx for the report.
