### ISSUE TITLE
Bad Garmin Connect username or password

### ISSUE THREAD

**Issue by TrippyZ** [kochka/WeightLogger#28]
The past week I haven't been able to upload.  I have been using your app for around a year so I now that Garmin break it from time to time!

Could you give it another kick please?

**Comment by TrippyZ** [comment]
I managed to solve this one.  It seems that about three weeks ago Garmin Connect came out with a update password policy which my password did not adhere.  I have now updated my Connect password and WeightLogger is now working.

**Comment by duncaninnes** [comment]
What is the new password policy? I updated my password, but still get the same error in WeightLogger.

**Comment by TrippyZ** [comment]
The app stopped working for me two months ago. I seem to recall Garmin announcing API license changes around the same time. 

Log a support ticket on git and perhaps Dev can get around it.

**Comment by kochka** [comment]
Duplicate #29

**Comment by kochka** [comment]
I've made a fix, I will publish it asap

**Comment by duncaninnes** [comment]
I saw an update through the store. Still not working in afraid. I cleaned cache, data, reinstalled completely. But no joy. Unless you haven't published the fix yet of course.

**Comment by kochka** [comment]
Strange, I've just retried now and works fine.
Furthermore I've got many feedback from users that it is working.
What version number is intalled on your mobile ? 2.1.2 ?

**Comment by duncaninnes** [comment]
Yup. 2.1.2

**Comment by kochka** [comment]
Do you try to log in using email or username ? Should be username but now I realise I should make it work with email...

**Comment by duncaninnes** [comment]
Changed to my username and the upload works. Will use these credentials for now. Cheers.

**Comment by kochka** [comment]
Thank you for the feedback, I will also make it work for email asap. Cheers.
