### ISSUE TITLE
Bad Garmin Connect username or password

### ISSUE THREAD

**Issue by duncaninnes** [kochka/WeightLogger#29]
Previously opened and closed by @TrippyZ as https://github.com/kochka/WeightLogger/issues/28

I changed my password with no effect to the upload error.

I modified my username to use my e-mail in case that was causing issue.  No change.

The Garmin Connect App is signing in properly with the same details.  Is there any advice on what the username/password requirements are for the API gateway?

**Comment by kochka** [comment]
Garmin do not provide any API.
To get a valid session, we need to manually proceed through the Connect login form, and this one is really shitty. I don't understand why it's not working anymore and debug I did drive me nowhere. All seems ok but I do not get a valid session at the end. I don't have a lot of time right now to investigate further, any help on this is welcome.
https://github.com/kochka/WeightLogger/blob/refactoring/app/src/main/java/org/kochka/android/weightlogger/tools/GarminConnect.java
