### ISSUE TITLE
Garmin Connect problem

### ISSUE THREAD

**Issue by MaiuZ** [kochka/WeightLogger#37]
I'm no longer able to upload to Garmin connect. It say that username and password are not correct even if I'm sure that they are correct.

**Comment by kochka** [comment]
Are you using username or email to log in ? Should be username until I fix
it...

2018-07-25 22:57 GMT+02:00 MaiuZ <notifications@github.com>:

**Comment by MaiuZ** [comment]
I've tried with username and email, but it's the same

Il mer 25 lug 2018, 23:21 kochka <notifications@github.com> ha scritto:

**Comment by kochka** [comment]
Sould be fixed with 2.3.0.
