### ISSUE TITLE
Lost data in backup

### ISSUE THREAD

**Issue by hayasaka0704** [kochka/WeightLogger#38]
When I export my data into CSV, there are 2309 records in it.
At the same time, I back up my data into a database, and 2272 records in SQLite database.
Backupable record count is limited?

**Comment by kochka** [comment]
Very strange ! If you still have this issue, send me your database file and I will check.

**Comment by hayasaka0704** [comment]
I tried backup & restore again, and all records are restored without problems.
I have no issue now. Thank you for your comment.

**Comment by kochka** [comment]
No pb :)
