### ISSUE TITLE
Import from openScale backup

### ISSUE THREAD

**Issue by FifiTheReal** [kochka/WeightLogger#43]
Dear kochka,

Can I import data from [openScale](https://github.com/oliexdev/openScale) backup file?
Here is [my backup file.](https://www.dropbox.com/s/bhtguwtd7cj6wcj/OpenScale-BackUp.sqlite3)

Thanks in advance!

**Comment by FifiTheReal** [comment]
I'm not a programmer but using google I writed a little script in ruby.
Restore database has faild and i don't know why.  :-(
[openScale-To-weightlogger.rb ](https://gist.github.com/FifiTheReal/d7c6cd5e8393aa537bfe02ac792104cd)

**Comment by alexanderadam** [comment]
@kochka is there any possibility to get some log / debug data in such cases?

**Comment by FifiTheReal** [comment]
I have writed new script. 
This adds new records to an existing backup of weightlogger from the database of openscale.
[new openScale-To-weightlogger.rb ](https://gist.github.com/FifiTheReal/43ed674c4f6bae0f199ff3a2c7e7675e)
