### ISSUE TITLE
No sync to Garmin field consumed calories

### ISSUE THREAD

**Issue by RobertWojtowicz** [kochka/WeightLogger#48]
No sync to Garmin Connect field consumed calories
In Garmin Connect, the field is empty

**Comment by Selduro** [comment]
Same for me. I don't know if garmin killed that feature because they are teaming up with myfitnesspal. 

Nontheless if it is possible I'd really appreciate that feature coming back since I really don't like mfp and cronometer (which I am using) cannot export the calories to garmin connect.
