### ISSUE TITLE
Question: how to connect to bluetooth scale?

### ISSUE THREAD

**Issue by alexanderadam** [kochka/WeightLogger#51]
I'm using Weight Logger `v2.3.2` but I cannot find any possibility to connect via Bluetooth.
Am I missing something?

Thank you in advance!

**Comment by FifiTheReal** [comment]
I use [openScale](https://github.com/oliexdev/openScale) with my [Sanitas SBF70](https://www.amazon.co.uk/Sanitas-70-Diagnostic-Connection-Smartphone-Measurements/dp/B00NABN36E).

Steps:
1. create backup from openScale
2. create backup from weightlogger
3. add measurements from backup of openScale to backup of weightlogger with [this script](https://gist.github.com/FifiTheReal/43ed674c4f6bae0f199ff3a2c7e7675e) on linux PC
4. restore new backup file in weightlogger
5. export to Garmin Connect from weightlogger

**Comment by alexanderadam** [comment]
Wow, what a complicated process.
Thank you for your script!

I just saw that you commented on [the corresponding openScale issue](https://github.com/oliexdev/openScale/pull/460) as well.
Do you have any idea [why this PR](https://github.com/oliexdev/openScale/pull/460) might have been closed?
