### ISSUE TITLE
Bad username/password error when uploading to Garmin Connect

### ISSUE THREAD

**Issue by ikanotheokara** [kochka/WeightLogger#53]
When I tried to sync data to Garmin Connect this morning, I got an error saying my username or password were incorrect. I've checked and double-checked and the username and password are both correct. Did something change in Garmin's API to break Weight Logger?

**Comment by rojamet** [comment]
Same problem here since today, looks like they did it again...

**Comment by Selduro** [comment]
Same.
Im sitting here for 30 minutes straight changing my password over and over again and nothing changed. Thought I was going crazy...

**Comment by kochka** [comment]
Ok, seems working, it was an easy fix. I'll will publish a new version.

**Comment by kochka** [comment]
APK is available for download here.
I will publish it on Play store asap but it seems my account need to be examined as I've just validated some stupid agreements.
Google is becoming as dumb as Apple....

**Comment by ikanotheokara** [comment]
Downloaded and installed the new APK and I can confirm that it works a treat! I'm glad it was a relatively easy fix and I hope you can get it on the Play store, soon. Thank you for responding so quickly.

Google policies seem to get worse every year, especially towards small and independent developers. I would really hate to see great projects like this killed due to red tape.

**Comment by kochka** [comment]
Thx for the feedback !

Agreed concerning Google, moreover they have stopped using their motto "Don't be evil" for good reasons lol
Even MS seems less evil now, what a shame... At least, MS has not destroyed Github yet

**Comment by Selduro** [comment]
@kochka 
> APK is available for download here.

I am somewhat embarassed I have to ask but where exactly can I download the new apk? I have not found a link.

**Comment by ikanotheokara** [comment]
Go to the code tab, scroll to the bottom where it says "releases" and click on the latest release. Here's a link to it:

https://github.com/kochka/WeightLogger/releases/tag/2.4.0

**Comment by Selduro** [comment]
Thank you!
If you'll ever integrate a donate button or publish a dono link I'll make sure to pay for your next couple of beers (or coffee whatever you prefer).

**Comment by RobertWojtowicz** [comment]
> 
> 
> Ok, seems working, it was an easy fix. I'll will publish a new version.

Can you explain what the problem was, I would like to add some additional information regarding the bug that probably affected another solution: https://github.com/davidkroell/bodycomposition/issues/10

I only created a direct sync connection from Xiaomi to Garmin, but this part of the solution not created by me, unfortunately, no longer works :(

**Comment by kochka** [comment]
It was just some new params that Garmin login expect to have if I remember well.
I've  quickly checked the repo you sent, but it use a library to connect to Garmin :
https://github.com/abrander/garmin-connect/blob/master/Client.go
