### ISSUE TITLE
 Bad username/password error when uploading to Garmin Connect

### ISSUE THREAD

**Issue by Selduro** [kochka/WeightLogger#57]
From the looks of it, garmin did it again (https://github.com/kochka/WeightLogger/issues/53).

Issue is the same:
I do get bad usernam/password since this morning when trying to upload to garmin connect. Yesterday everthing was working fine.
My credentials are still working when logging into garmin connect via webbrowser myself.

**Comment by kochka** [comment]
I'll get a look

**Comment by kochka** [comment]
Seems to be a 1020 Cloudflare protection error...

**Comment by kochka** [comment]
I've fixed the Cloudflare issue by faking the user agent but now there is a F. file storage issue... Can't anymore of Google changing API all the time...

**Comment by kochka** [comment]
Fixed in 472d49ee
