### ISSUE TITLE
Garmin connect stopped working (05-2021)

### ISSUE THREAD

**Issue by DarkwellZ** [kochka/WeightLogger#58]
Garmin Connect reports "Bad username of password". Checked many times, they are correct.
Other tools (HomeAssistant smart home platform) also stopped working so I believe it to be caused by a change in Garmins platform.

**Comment by cerealpiller** [comment]
Same for me

**Comment by kochka** [comment]
Should have been fixed with 2.4.2, what version are you using ?

**Comment by DarkwellZ** [comment]
Working again for me. Im on 2.4.2. it reports "updated 13 hours ago"

**Comment by cerealpiller** [comment]
Says 2.4.2 been 3-4 days with the wrong user/pass error

**Comment by kochka** [comment]
@cerealpiller Strange, this issue should have been fixed in 2.4.2. Can you check again that is it not working ?

**Comment by cerealpiller** [comment]
It did work this morning. Thanks again for your help

**Comment by kochka** [comment]
Ah cool to hear, thx !
