### ISSUE TITLE
Garmin export username/password

### ISSUE THREAD

**Issue by lolo406** [kochka/WeightLogger#62]
Bonjour, 
 L'application fonctionne bien, mais à chaque fois que j'essaie d'exporter vers Garmin, ça m'indique erreur de username/password, depuis le 19mai.
J'ai réinstallé l'application, et pas d'évolution.
Comment dois je procéder ?
Merci

**Comment by cerealpiller** [comment]
Is there a new fix? still getting user/password error. Im on 2.4.2

**Comment by lolo406** [comment]
Bonjour, Ca refonctionne depuis eviron 1 mois.... je n'ai pas d'explication à ça, je dirais que c'est retombé en marche. Merci pour l'application en tout cas
